name: Can update TargetFrameworks
description: Checks if TargetFrameworks can be updated
inputs:
  project:
    required: true
    description: "Allowed values: EFCore.IncludeByExpression | EFCore.IncludeByExpression.Abstractions"
  target-dotnet-versions:
    required: true
    description: "Allowed values: string[]"
outputs:
  result:
    description: "true | false"
    value: "${{ steps.validate.outputs.result }}"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Validate
      shell: pwsh
      id: validate
      run: |
        Write-Host "Selected project: ${{ inputs.project }}"
        Write-Host "Target .NET versions (raw): ${{ inputs.target-dotnet-versions }}"
        $TargetDotnetVersions = "${{ inputs.target-dotnet-versions }}" -split ","
        Write-Host "Parsed target versions:" ($TargetDotnetVersions -join ", ")
        $SelectedProject = "${{ inputs.project }}"
        $csProjPath = "$([IO.Path]::Combine(".", "$($SelectedProject)", "$($SelectedProject).csproj"))"
        Write-Host "Project file path: $csProjPath"
        $csprojXml = [xml](Get-Content $csProjPath)
        Write-Host "Loaded .csproj XML."
        $projectTargetFrameworksStr = $csprojXml.Project.PropertyGroup.TargetFrameworks
        if (![string]::IsNullOrWhitespace($projectTargetFrameworksStr)) {
          Write-Host "Detected multi-targeting: $projectTargetFrameworksStr"
          $projectTargetFrameworks = @($projectTargetFrameworksStr -split ';' -match '\S')
          Write-Host "Parsed project frameworks:" ($projectTargetFrameworks -join ", ")
          $hasDifferences = [Bool](Compare-Object -ReferenceObject $projectTargetFrameworks -DifferenceObject $TargetDotnetVersions)
          Write-Host "Differences detected between project and target versions: $hasDifferences"
          "result=$("$($hasDifferences)".ToLowerInvariant())" >> $env:GITHUB_OUTPUT
          exit 0  
        }
        $projectTargetFramework = $csprojXml.Project.PropertyGroup.TargetFramework
        Write-Host "Single TargetFramework detected: $projectTargetFramework"
        if ([string]::IsNullOrWhitespace($projectTargetFramework)) {
          Write-Host "No TargetFrameworks or TargetFramework found in $csProjPath"
          exit 1
        }
        if ($projectTargetFramework -like 'netstandard*') {
          Write-Host "Project targets netstandard; no update required."
          "result=false" >> $env:GITHUB_OUTPUT
          exit 0
        }
        Write-Host "Processing numeric comparison for single TargetFramework..."
        $numericVersions = @($TargetDotnetVersions | ForEach-Object { 
          $numericValue = [decimal]($_ -replace "^net")
          Write-Host "Parsed numeric target version: $numericValue"
          $numericValue
        })
        
        $checkNumeric = [decimal]($projectTargetFramework -replace "^net")
        Write-Host "Parsed numeric project version: $checkNumeric"
        
        $highestVersion = ($numericVersions | Measure-Object -Maximum).Maximum
        Write-Host "Highest target version: $highestVersion"
        Write-Host "Project version: $checkNumeric"
        $needsUpdate = $checkNumeric -ne $highestVersion
        Write-Host "Does project need update? $needsUpdate"
        "result=$("$($needsUpdate)".ToLowerInvariant())" >> $env:GITHUB_OUTPUT