name: Setup git
description: Setup git
inputs:
  branch:
    description: branch
    required: true
  hard-reset:
    description: "Branch name to which hard reset"
    required: false
runs:
  using: "composite"
  steps:
    - name: setup
      shell: bash
      run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          TARGET_BRANCH_NAME="${{ inputs.branch }}"
          IS_TARGET_BRANCH_EXISTS=$(git ls-remote --heads origin $TARGET_BRANCH_NAME | grep -q "refs/heads/$TARGET_BRANCH_NAME" && echo true || echo false)
          echo "IS_TARGET_BRANCH_EXISTS=$IS_TARGET_BRANCH_EXISTS" >> $GITHUB_ENV
          if [[ "$IS_TARGET_BRANCH_EXISTS" == "true" ]]; then
            git fetch origin $TARGET_BRANCH_NAME:$TARGET_BRANCH_NAME
            if [ `git rev-parse --verify $TARGET_BRANCH_NAME 2>/dev/null` ]
            then
              git checkout $TARGET_BRANCH_NAME
            else
              git checkout --track -b $TARGET_BRANCH_NAME origin/$TARGET_BRANCH_NAME
            fi

            if [[ "${{ inputs.hard-reset }}" != "" ]]; then
              git reset --hard origin/${{ inputs.hard-reset }}
            fi
          else
            echo "#1"
            if [[ "${{ inputs.hard-reset }}" != "" ]]; then
              git fetch origin ${{ inputs.hard-reset }}
              echo "#2"
              git checkout --no-track -b $TARGET_BRANCH_NAME refs/heads/${{ inputs.hard-reset }}
            else
              echo "#3"
              git checkout -b $TARGET_BRANCH_NAME
            fi
          fi

