name: Update nuspec file
description: Update .nuspec file
inputs:
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true
  project:
    required: true
    description: "Allowed values: EncryptedConfigValue.Module | EncryptedConfigValue.AspNetCore | EncryptedConfigValue.Cli"
  dotnet-version:
    required: true
    description: "Indicates release branch from which changes will be deployed"
  external-dependencies-sources:
    required: false
    description: "Allowed values: (EncryptedConfigValue | EncryptedConfigValue.Module | EncryptedConfigValue.AspNetCore | EncryptedConfigValue.Cli)[]"
  additional-files:
    required: false
    description: "Allowed values: string[]"
runs:
  using: "composite"
  steps:
      - uses: ./.github/actions/setup-dotnet-action
    
      - name: Build
        shell: bash
        run: dotnet build ./EncryptedConfigValue.sln --configuration Release

      - name: Update ${{ inputs.project }}.nuspec
        shell: bash
        run: |
          external_dependencies_paths=""
          if [ -n "${{ inputs.external-dependencies-sources }}" ]; then
            EXTERNAL_DEPENDENCIES_SOURCES=$(echo "${{ inputs.external-dependencies-sources }}" | grep -v '^$' | tr '\n' ',' | sed 's/, *,/,/g; s/,$//')
            IFS=',' read -r -a dependencies_array <<< "$EXTERNAL_DEPENDENCIES_SOURCES"
            for dependency in "${dependencies_array[@]}"; do
              path="./$dependency/$dependency.csproj"
              if [ -z "$external_dependencies_paths" ]; then
                external_dependencies_paths="'$path'"
              else
                external_dependencies_paths="$external_dependencies_paths,'$path'"
              fi
            done
          fi    

          external_dependencies_param=""
          if [ -n "$external_dependencies_paths" ]; then
            external_dependencies_param="-ExternalCsprojDependencies $external_dependencies_paths"
          fi
          
          additional_files_paths=""
          if [ -n "${{ inputs.additional-files }}" ]; then
            ADDITIONAL_FILES=$(echo "${{ inputs.additional-files }}" | grep -v '^$' | tr '\n' ',' | sed 's/, *,/,/g; s/,$//')
            IFS=',' read -r -a additional_files_array <<< "$ADDITIONAL_FILES"
            for path in "${additional_files_array[@]}"; do
              if [ -z "$additional_files_paths" ]; then
                additional_files_paths="'$path'"
              else
                  additional_files_paths="$additional_files_paths,'$path'"
              fi
            done
          fi

          additional_files_param=""
          if [ -n "$additional_files_paths" ]; then
            additional_files_param="-AdditionalFiles $additional_files_paths"
          fi

          cmd="pwsh -Command ./Scripts/UpdateNuspec.ps1 -CsprojPath './${{ inputs.project }}/${{ inputs.project }}.csproj' -NuspecPath './${{ inputs.project }}/${{ inputs.project }}.nuspec' $external_dependencies_param $additional_files_param"
          echo $cmd
          eval "$cmd"
          echo "Finished"
