name: Put Pull Request
description: Creates pull request
inputs:
  GITHUB_TOKEN:
    description: GITHUB_TOKEN
    required: true
  title:
    description: Title of PR
    required: true
  body:
    description: Body of PR
    required: true
  from:
    description: From branch name
    required: true
  into:
    description: Target branch name
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Create Pull Request
      shell: bash
      run: |
        pr_id=$(gh pr list --head ${{ inputs.from }} --base ${{ inputs.into }} --json number --jq '.[0].number')
        if [ -z "$pr_id" ]; then
          gh pr create -B ${{ inputs.into }} -H ${{ inputs.from }} --title "${{ inputs.title }}" --body "${{ inputs.body }}"
        else
          gh pr edit $pr_id --title "${{ inputs.title }}" --body "${{ inputs.body }}"
        fi
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

