name: tests
env:
# dotnet-framework to dotnet-version maps
  "netstandard2.0": 3.1.x
  "netstandard2.1": 3.1.x
  "net8.0": 8.0.x
# dotnet-version to target framework map
  "3.1.x": netcoreapp3.1
  "8.0.x": net8.0
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: tests-${{ matrix.operating-system }}-dotnet-${{ matrix.dotnet-framework }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        dotnet-framework: [ netstandard2.0, netstandard2.1, net8.0 ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env[matrix.dotnet-framework] }}
    - name: Build project
      run: dotnet build ./EFCore.NavigationPropertyPathSchema/EFCore.NavigationPropertyPathSchema.csproj --configuration Release --framework ${{ matrix.dotnet-framework }}
    - name: Build tests project
      run: dotnet build ./EFCore.NavigationPropertyPathSchema.Tests.Unit/EFCore.NavigationPropertyPathSchema.Tests.Unit.csproj --configuration Release --framework ${{ env[env[matrix.dotnet-framework]] }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal --framework ${{ env[env[matrix.dotnet-framework]] }}
