name: Test
on:
  pull_request:
  push:
    branches:
      - main
      - 'release/**'
  merge_group:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 0 || 1 }}
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Merge latest target branch
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git merge origin/${{ github.event.pull_request.base.ref }} --no-edit
      
      - uses: ./.github/actions/setup-dotnet
      - name: Build
        run: dotnet build . --configuration Debug
      - name: Test
        run: dotnet test --no-restore --verbosity normal
